apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-example-app
  labels:
    app: python-example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-example-app
  template:
    metadata:
      labels:
        app: python-example-app
    spec:
      containers: 
      - name: python-example-app
        image: prabha916/python-example-app:v1
        ports:
        - containerPort: 8000

